resources:
- name: java-app-src
  type: git
  source:
    uri: https://github.com/cloudfoundry-samples/spring-music

- name: app-to-PCF
  type: git
  source:
    uri: https://github.com/mambrose-pivotal/jar-pipelines

- name: resource-deploy-java-app
  type: cf
  source:
    api: {{cf-api}}
    username: {{cf-username}}
    password: {{cf-password}}
    organization: {{cf-organization}}
    space: {{cf-space}}
    skip_cert_check: true

jobs:
-name: build-java-app
  serial: true
  plan:
    - get: java-app-src
    - get: app-to-PCF
    - task: build-java-app
      file: app-to-PCF/task-buildapp.yml

- name: job-deploy-app
  serial: true
  plan:
  - get: resource-java-app
    trigger: tru
  - put: resource-deploy-java-app
    params:
      manifest: resource-java-app/manifest.yml
      path: resource-java-app
